spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
app:
  storage:
    location: ./uploads/
server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
    path: /error