

spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  h2:
    console:
      enabled: true
  web:
      resources:
        static-locations: classpath:/static/,file:./uploads/
app:
      storage:
        location: ./uploads/